services:
  - type: web
    name: expense-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    plan: free
